name: example
on:
  push:
    branches:
      - master
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Deploy
        uses: mooyoul/cloudwatch-logs-actions@v1.1.2
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          group: cloudwatch-logs-actions-example
          stream: ${{ github.sha }}
          retention: 14 # 14 days
          shell: bash
          run: |
            echo 'hello world'
            ls -al
            curl http://api.ipify.org/ --verbose
